# Generated by Django 5.2 on 2025-07-18 03:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wardriving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mac", models.CharField(max_length=17, verbose_name="MAC Address")),
                (
                    "ssid",
                    models.CharField(default="", max_length=255, verbose_name="SSID"),
                ),
                (
                    "auth_mode",
                    models.CharField(
                        default="", max_length=50, verbose_name="Authentication Mode"
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="First Seen"
                    ),
                ),
                ("channel", models.IntegerField(verbose_name="Channel")),
                ("rssi", models.IntegerField(verbose_name="RSSI (Signal Strength)")),
                (
                    "current_latitude",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=9,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "current_longitude",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=9,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "altitude_meters",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Altitude (Meters)",
                    ),
                ),
                (
                    "accuracy_meters",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Accuracy (Meters)",
                    ),
                ),
                (
                    "device_source",
                    models.CharField(
                        choices=[
                            ("unknown", "unknown"),
                            ("minino", "minino"),
                            ("flipper dev board", "flipper dev board"),
                            ("flipper dev board pro", "flipper dev board pro"),
                            ("marauder v4", "marauder v4"),
                            ("marauder v6", "marauder v6"),
                            ("flipper bffb", "flipper bffb"),
                            ("marauder esp32", "marauder esp32"),
                            ("other", "other"),
                        ],
                        default="unknown",
                        max_length=50,
                        verbose_name="Source",
                    ),
                ),
                (
                    "uploaded_by",
                    models.TextField(default="", verbose_name="Uploaded by"),
                ),
            ],
            options={
                "verbose_name": "Wardriving Data",
                "verbose_name_plural": "Wardriving Data",
                "db_table": "wardriving",
            },
        ),
    ]
