# Generated by Django 5.2 on 2025-07-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wardriving", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wardriving",
            name="type",
            field=models.CharField(default="WIFI", max_length=50, verbose_name="Type"),
        ),
    ]
