# Generated by Django 5.2 on 2025-09-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wardriving", "0002_wardriving_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="LTEWardriving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mcc", models.IntegerField(verbose_name="MCC (Mobile Country Code)")),
                ("mnc", models.IntegerField(verbose_name="MNC (Mobile Network Code)")),
                ("lac", models.IntegerField(verbose_name="LAC (Location Area Code)")),
                (
                    "cell_id",
                    models.IntegerField(verbose_name="Cell ID (Cell Global Identity)"),
                ),
                ("band", models.TextField(verbose_name="Band")),
                ("rssi", models.IntegerField(verbose_name="RSSI (Signal Strength)")),
                (
                    "rsrp",
                    models.IntegerField(
                        verbose_name="RSRP (Reference Signal Received Power)"
                    ),
                ),
                (
                    "rsrq",
                    models.IntegerField(
                        verbose_name="RSRQ (Reference Signal Received Quality)"
                    ),
                ),
                (
                    "sinr",
                    models.IntegerField(
                        verbose_name="SINR (Signal-to-Interference-plus-Noise Ratio)"
                    ),
                ),
                ("provider", models.TextField(default="", verbose_name="Provider")),
                (
                    "current_latitude",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=9,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "current_longitud",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=9,
                        verbose_name="Longitude",
                    ),
                ),
            ],
            options={
                "verbose_name": " LTE Wardriving Found",
                "verbose_name_plural": " LTE Wardriving Founds",
                "db_table": "lte_wardriving",
            },
        ),
        migrations.AlterField(
            model_name="wardriving",
            name="device_source",
            field=models.CharField(
                choices=[
                    ("unknown", "unknown"),
                    ("minino", "minino"),
                    ("flipper dev board", "flipper dev board"),
                    ("flipper dev board pro", "flipper dev board pro"),
                    ("marauder v4", "marauder v4"),
                    ("marauder v6", "marauder v6"),
                    ("flipper bffb", "flipper bffb"),
                    ("marauder esp32", "marauder esp32"),
                    ("rf custom firmware wifi", "rf custom firmware wifi"),
                    ("rf custom firmware lte", "rf custom firmware lte"),
                    ("other", "other"),
                ],
                default="unknown",
                max_length=50,
                verbose_name="Source",
            ),
        ),
    ]
