# Generated by Django 5.2 on 2025-11-03 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "wardriving",
            "0006_ltewardriving_created_at_ltewardriving_deleted_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="ltewardriving",
            old_name="current_longitud",
            new_name="current_longitude",
        ),
    ]
