# Generated by Django 5.2 on 2025-07-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FilesUploaded",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.FileField(upload_to="wardrive_sources/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.TextField(default="", verbose_name="Uploaded by"),
                ),
                (
                    "device_source",
                    models.CharField(
                        choices=[
                            ("unknown", "unknown"),
                            ("minino", "minino"),
                            ("flipper dev board", "flipper dev board"),
                            ("flipper dev board pro", "flipper dev board pro"),
                            ("marauder v4", "marauder v4"),
                            ("marauder v6", "marauder v6"),
                            ("flipper bffb", "flipper bffb"),
                            ("marauder esp32", "marauder esp32"),
                            ("other", "other"),
                        ],
                        default="unknown",
                        max_length=50,
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Upload",
                "verbose_name_plural": "Files Upload",
                "db_table": "file_upload",
            },
        ),
    ]
