# Generated by Django 5.2 on 2025-07-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesuploaded",
            name="is_procesed",
            field=models.BooleanField(default=False),
        ),
    ]
