# Generated by Django 5.2 on 2025-07-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_filesuploaded_is_procesed"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowToLoadData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "allow_to_load_data",
            },
        ),
    ]
