# Generated by Django 5.2 on 2025-11-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0004_alter_filesuploaded_device_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesuploaded",
            name="hash_sha256",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
    ]
