# Generated by Django 5.2 on 2025-11-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0005_filesuploaded_hash_sha256"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourcesWithCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_author",
                    models.TextField(default="", verbose_name="Original author"),
                ),
                (
                    "fake_author",
                    models.TextField(default="", verbose_name="Fake author"),
                ),
                (
                    "hash_sha256",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
            ],
            options={
                "db_table": "sources_with_copy",
            },
        ),
    ]
